name: Deploy web-interface

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - uses: google-github-actions/setup-gcloud@v2

      - name: Deploy
        run: |
          gcloud run deploy web-interface \
            --source . \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars ITEM_URL=https://lost-found-item-service-512993707354.us-central1.run.app,SEARCH_URL=https://search-service-512993707354.us-central1.run.app,AUTH_URL=https://auth-service-512993707354.us-central1.run.app \
            --quiet
